Add `classList` + functions of `DOMTokenList`
purescript-contrib/purescript-dom pull request #106
Opened 2017-06-09 15:49 UTC by sectore

- All the following functions of `DOMTokenList` are added and supported by all modern
browsers (see https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList):
  * `add`
  * `remove`
  * `toggle`
  * `contains`
  * `item`

- incl. tests (depends on PR #105 )

![domtokenlist-tests](https://user-images.githubusercontent.com/47693/26983329-b07e3822-4d3b-11e7-9cb7-cf4bf6211f9a.png)

2017-06-10 19:18 UTC, garyb requested changes
Thanks for working on this! Just a few minor things, and this PR needs a rebase since the test PR was merged.

2017-06-10 19:18 UTC, garyb commented on test/Main.purs
> +-- liftEff = EffClass.liftEff
Dead code

2017-06-10 19:18 UTC, garyb commented on src/DOM/Node/DOMTokenList.purs
> +item index = map toMaybe <<< _item index
Can you rearrange the arguments in here (and accordingly in the FFI) so the `DOMTokenList` comes first in each case please?

2017-06-11 08:28 UTC, sectore commented
@garyb No problem, latest commits ⬆️  come with these fixes (rebase + rearrange arguments).

2017-06-11 13:07 UTC, garyb commented
Thank you!

2017-06-11 13:07 UTC, garyb approved these changes

2017-06-11 13:07 UTC, merged