Add dropEffect getter and setter on DataTransfer
purescript-contrib/purescript-dom pull request #140
Opened 2017-12-25 17:54 UTC by fehrenbach

2018-01-20 18:00 UTC, garyb requested changes
Your PR to Halogen reminded me of this one that has been outstanding for ages. Sorry about the delay!

2018-01-20 18:00 UTC, garyb commented on src/DOM/HTML/Event/DataTransfer.purs
> +    "none" -> None
`unsafePartialBecause` is problematic (https://github.com/purescript/purescript-partial/issues/7), could you use `crashWith` in an `_` case, and then `unsafePartial` the `case` instead please?

2018-01-20 18:00 UTC, garyb commented on src/DOM/HTML/Event/DataTransfer.purs
> +data DropEffect = None | Copy | Move | Link
Could you add derived instances for `Eq` and `Ord` for this too please?

2018-01-21 12:48 UTC, fehrenbach commented
No worries. What kind of heathen makes pull requests on Christmas Day anyways? ;)

Thanks for the review. I addressed your remarks and sorted the cases while I was at it.

2018-01-21 14:14 UTC, garyb commented
Thanks!

2018-01-21 14:14 UTC, garyb approved these changes

2018-01-21 14:14 UTC, merged