Added some window functions and unit tests
purescript-contrib/purescript-dom pull request #64
Opened 2016-10-09 23:02 UTC by Risto-Stevcev

2016-10-20 14:12 UTC, garyb commented
Thanks for working on these. I'll come back to this later once `Aff` has been updated (for the tests).

2016-10-22 17:17 UTC, garyb commented
`Aff` can be bumped to 2.0.0 now, which hopefully will get things passing again.

2016-10-22 20:38 UTC, Risto-Stevcev commented
@garyb Got the checks to pass

2016-10-23 13:41 UTC, garyb requested changes
Thanks for working on these! There's a few things I'd like removed or updated before merging though.

2016-10-23 13:41 UTC, garyb commented on src/DOM/HTML/Window.purs
> +foreign import closed :: forall eff. Window -> Eff (window :: WINDOW | eff) Boolean
Please remove this, it's a nonstandard property - this library is intentionally only implementing standards, even when things are commonly available.

2016-10-23 13:41 UTC, garyb commented on src/DOM/HTML/Window.purs
> +foreign import minimize :: forall eff. Window -> Eff (window :: WINDOW | eff) Unit
Please remove this one too.

2016-10-23 13:41 UTC, garyb commented on src/DOM/HTML/Window.purs
> +  -> Eff (window :: WINDOW | eff) (Maybe Window)
You could implement this with `Nullable` instead and then use `toMaybe`. Something like this:

https://github.com/purescript-contrib/purescript-dom/blob/f7b786d9f005df0a41b1da63d3525b8d8ae55457/src/DOM/HTML/Event/DragEvent/DataTransfer.purs#L20-L23

The FFI code can just be currying then, with no need to handle the `Nothing` / `Just` arguments.

2016-10-23 13:41 UTC, garyb commented on src/DOM/HTML/Window.purs
> +  -> Eff (prompt :: PROMPT | eff) (Maybe String)
Another case where `Nullable` can be used.

2016-10-23 15:25 UTC, Risto-Stevcev commented
@garyb Updated it

How do you feel about extending purescript-nullable to have `Undefinable` and `NullOrUndefinable`? `Nullable` is a lot easier to use than `Data.Foreign.Null`, but it doesn't have the equivalent `Data.Foreign.Undefined` and `Data.Foreign.NullOrUndefined`

2016-10-23 15:44 UTC, garyb commented
`Nullable` is already `NullOrUndefined`, as it's not intended for precise data format matching like `Foreign` is - it's just a helper for when you have functions that might not return a value. Is the distinction necessary here? I wouldn't have though so.

2016-10-23 15:46 UTC, garyb requested changes
Sorry, just noticed another thing - the argument orders are all "javascripty" rather than "purescripty" - `window` should be the last argument in each case, as then you can do things like:

``` purescript
alert "hi" =<< window
```

2016-10-23 17:03 UTC, Risto-Stevcev commented
Rearranged it

2016-10-23 20:20 UTC, garyb approved these changes

2016-10-23 20:20 UTC, garyb commented
Thanks!

2016-10-23 20:20 UTC, merged