Add DOM.HTML.History.
purescript-contrib/purescript-dom pull request #75
Opened 2017-01-19 18:01 UTC by chexxor

The type signature of `state` might be wrong: `state :: forall a e. History -> Eff (history :: HISTORY | e) a`. I'm not using it, but after some brief exploring of that property I believe it could be *any* shape, so I put `a`. The browser puts one type of data in there, but users could put any type there via `pushState`, per the history spec.

2017-01-19 18:05 UTC, garyb commented
I think `Foreign` would be a better choice than leaving `state` polymorphic in its return value then perhaps?

2017-01-19 18:06 UTC, chexxor commented
Oh good idea. I'll do the same for `pushState`.

2017-01-19 20:32 UTC, garyb commented
Can you make Travis happy? It's just lint/style stuff, the fixes can probably be applied automatically.

2017-01-21 01:32 UTC, chexxor commented
Thanks @garyb. I don't know how I missed those warnings. I probably did `pulp build` instead of `npm run build`. Pushed a commit to fix.

2017-01-21 14:12 UTC, garyb requested changes
Sorry, I noticed a few other things. This'll be the end of the requests, honest!

2017-01-21 14:12 UTC, garyb commented on src/DOM/HTML/History.purs
> +foreign import state :: forall e. History -> Eff (history :: HISTORY | e) Foreign
Sorry I didn't notice this earlier, but can we put the `History` argument at the end for all of these? That's more consistent with the rest of the API, and is done so you can write things like:

``` purescript
go -2 =<< history =<< window
```

2017-01-21 14:12 UTC, garyb commented on src/DOM/HTML/History.purs
> +newtype URL = URL String -- Unsure how to better type this.
Can you derive `Eq`, `Ord`, and `Newtype` instances for these please?

I know what you mean about `URL`, but I think it's fine as a newtype here, as the API we're providing with this library is supposed to be dumb anyway.

2017-01-21 14:12 UTC, garyb commented on src/DOM/HTML/History.js
> +// module DOM.HTML.History
We can drop these comments now, the compiler switched to using paths to figure out associated FFI files a few versions ago.

2017-01-24 04:04 UTC, chexxor commented on src/DOM/HTML/History.purs
> +foreign import state :: forall e. History -> Eff (history :: HISTORY | e) Foreign
I followed the pattern in Location module, but I see those functions only have one arg, but I look closer and see you're right. I'll update.

2017-01-24 04:04 UTC, chexxor commented on src/DOM/HTML/History.js
> +// module DOM.HTML.History
Ah neat, I didn't know that - I thought it was purely convention.

2017-01-24 04:04 UTC, chexxor commented on src/DOM/HTML/History.purs
> +newtype URL = URL String -- Unsure how to better type this.
Adding.

2017-01-24 04:13 UTC, chexxor commented
Awesome suggestions. I've updated and pushed a new commit.

2017-01-25 21:09 UTC, garyb requested changes
Everything looks great now apart from one thing... need to update the FFI implementations to move `history` to the last argument too! :smile:

2017-01-25 21:25 UTC, chexxor commented
Ah, yeah, good catch. I am using this branch in my project but I didn't update to this latest commit yet. I should do that to provide some assurance it's working as it should. I'll post here after I've done that. It'll be 1-3 days, I guess.

2017-02-14 12:16 UTC, garyb commented
Thanks!

2017-02-14 12:16 UTC, merged

2017-02-14 19:25 UTC, chexxor commented
I haven't finished testing this in my app, but that's fine b/c I can just make another MR if I need to fix something. Thanks @garyb for reviewing!