Request animation frame
purescript-contrib/purescript-dom pull request #91
Opened 2017-04-13 13:53 UTC by coot

Completes #90.

2017-04-15 10:11 UTC, garyb requested changes
Thanks! Just a couple of things that could use tweaking / discussion.

2017-04-15 10:11 UTC, garyb commented on src/DOM/HTML/Window.js
> +    return window.cancelAnimationFrame(id);
Need an extra `function() {` wrapping the inner thing here as we're `Eff`-typing these things.

2017-04-15 10:11 UTC, garyb commented on src/DOM/HTML/Window.js
> +    return window.cancelIdleCallback(id);
Same with this one!

2017-04-15 10:11 UTC, garyb commented on src/DOM/HTML/Window.purs
> +derive instance newtypeRequestAnimationFrameId :: Newtype RequestAnimationFrameId _
Can you derive `Eq` and `Ord` for both of the newtypes introduced in here please?

2017-04-15 10:11 UTC, garyb commented on src/DOM/HTML/Window.purs
> +requestIdleCallback :: forall eff. Eff (dom :: DOM | eff) Unit -> { timeout :: Int } -> Window -> Eff (dom :: DOM | eff ) RequestIdleCallbackId
Maybe we should put the options first here? Seems like a more natural ordering for currying perhaps.

Also, is `timeout: 0` different from not specifying a value at all? If so, I guess we'll have to provide two varieties of `requestIdleCallback` to either accept options or not / have `Maybe` properties or something.

2017-04-15 11:48 UTC, coot commented on src/DOM/HTML/Window.purs
> +requestIdleCallback :: forall eff. Eff (dom :: DOM | eff) Unit -> { timeout :: Int } -> Window -> Eff (dom :: DOM | eff ) RequestIdleCallbackId
The spec says that the timeout is only taken into account if it is a [positive integer](https://w3c.github.io/requestidlecallback/#h-the-requestidlecallback-method).

2017-04-17 18:50 UTC, garyb commented
Thanks for making those changes, and adding the comment about 0 timeout. Just need those additional updates to the JS (adding the thunk for `Eff`), and also need to swap the arguments in the FFI to reflect the change in the PS file now.

2017-04-17 18:56 UTC, coot commented
Ups, I forgot to commit them. Here there are :)

2017-04-22 01:21 UTC, garyb approved these changes

2017-04-22 01:21 UTC, garyb commented
Thanks!

2017-04-22 01:21 UTC, merged